WINDOW_HEIGHT = 1080
ASPECT_RATIO = 16.0 / 9.0

WINDOW_WIDTH = int(WINDOW_HEIGHT * ASPECT_RATIO)

SCALE_FACTOR = 1

STATIC_RENDER = False
STATIC_RENDER_ANIMATION = False

DYNAMIC_RENDER_FRAMERATE = 144

MAX_RAY_BOUNCES = 4
RAYS_PER_PIXEL = 1

STATIC_RENDER_FRAMERATE = 144
STATIC_RENDER_CYCLES_PER_FRAME = 256
STATIC_RENDER_TIME_DURATION = 2.0
